### ISSUE TITLE
Edit Sheet Music

### ISSUE THREAD

**Issue by eatthoselemons** [niveK77pur/VinLudens_Music-Sheets#1]
What is the best program to edit the sheet music? I am trying to make an easier version of Kyou Yamai Bunko by removing some of the notes and wondering how you edit? The program I usually use MuseScore doesn't work with .ly files

**Comment by niveK77pur** [comment]
Hello! I primarily use [Frescobaldi](https://www.frescobaldi.org/) to edit and write my sheet music and I think it has a few neat features to assist writing Lilypond. It seems to me that you cannot read the Lilypond files directly into MuseScore unfortunately.

Looking around a little though, there seems to be a way to export the Lilypond code to *MusicXML* which can in turn be imported in MuseScore from what I understand. I have never used it before though so I will have to try it at a later time if you are having difficulties with Lilypond and/or Frescobaldi.

I should also say that Lilypond is actually text-based (I think of it as LaTeX but for music), so there is technically no direct equivalent to MuseScore. However, Frescobaldi shows you the Lilypond code on the left pane, and the output PDF on the right pane. A neat feature of Frescobaldi is that you can click on notes in the PDF and it gets you right to where that is located in the source code; I think this is very handy for modifying the score.

I also assume you have never used Lilypond or Frescobaldi before so let me give you some hints and small resources to get started.
- <https://lilypond.org/text-input.html> gives a nice and brief overview on the syntax
- <https://www.youtube.com/playlist?list=PLHi8BvxILUV6x9FqEmZiYrEj6VMGmTKjt> this is a very nice tutorial playlist on YouTube which goes over the basics of Lilypond and how to work with it using Frescobaldi (only the first few videos should be relevant)

Hope this is of any help! :smile:  If not or you're not willing to dive into Lilypond, let me know either way and I will look into the *MusicXML* thing. It seems to be a very nice bridge for transferring scores between different editors.

---

You can find a more exhaustive list of editors for Lilypond here: <https://lilypond.org/easier-editing.html>

And for myself regarding the MusicXML I'll just put the following for reference:
- <https://musescore.org/en/node/285188>
- <https://groups.google.com/g/frescobaldi/c/uuuBmK4zubE?pli=1>

**Comment by eatthoselemons** [comment]
Thanks for the quick reply!

I was messing around with Frescobaldi and my edits seemed to be messing the sheet music up a bunch, I will try again with that tutorial

Based on the time I have spent on Frescobaldi I probably won't spend much more on it. I am definitely a beginner and I don't know if I can modify yours to make it down to my level. So I am leaning towards just paying someone to transcribe some of the music into super beginner music

Thanks though for your music, it is great to listen to!

**Comment by niveK77pur** [comment]
Yes I can imagine that the text-based nature can be quite confusing and disorienting if one is not used to it. It takes some practice but personally I think it is worth the effort because of how gorgeous everything looks by default. But I understand that not everyone is masochistic enough to go that route and leave the comfort of a proper GUI application lol

I also just had a quick look at Frescobaldi's MusicXML export functionality but it sadly does not work out of the box for this score. This export feature is actually still experimental and is not very optimal, only serving as a response to Lilypond itself lacking such capability (as [stated Frescobaldi's python-ly github wiki](https://github.com/frescobaldi/python-ly/wiki/Export-LilyPond-to-MusicXML))

WIth the few things I tried, I feel like I'd have to dig a little further in order to make the score exportable to MusicXML (I kept getting errors while attempting to do so). Maybe I'll even be able to create a few more [issues on the python-ly repository](https://github.com/frescobaldi/python-ly/labels/musicxml%20export) because at a glance there were none related to what I encountered (although I should look at the closed issues as well, maybe there exist solutions afterall).

I am very sorry for the inconvenience but I am afraid there is little that can be done at this point in time except using Lilypond directly, or copying the score into MuseScore by hand. I'll leave this issue open as I expect most folk would be more interested in editing the scores in something like MuseScore. Thanks as well for bringing up the issue though!

**Comment by eatthoselemons** [comment]
Yea it can get pretty confusing!

Also thanks for checking musicXML, sad it doesn't work out of the box but maybe one day!

You are welcome and thanks for replying so quickly!

**Comment by niveK77pur** [comment]
Small update on the situation. I randomly stumbled upon the `ly` command which also can export to musicxml. However it does not work for the Kyou Yamai Bunko sheets, giving me an error. It does mention in the docs though that's it's still far from complete, but this might be interesting (for me) to keep an eye out for.

Command I ran
```bash
$ ly musicxml Kyou-Yamai-Bunko.ly > myscore.musicxml
```

---

Where I found out about it: <https://music.stackexchange.com/questions/42315/lilypond-to-musicxml-to-sibelius#73706>
The docs: https://python-ly.readthedocs.io/en/latest/command.html#commands

**Comment by eatthoselemons** [comment]
That is cool that there is work on exporting to musicxml! Hopefully, the command gets fixed soon!

Also thanks for watching this issue!

**Comment by niveK77pur** [comment]
Hello my friend, it has been a while! Sadly, no updates on the musicxml situation (at least none that I know of).

However, I am going to archive this repository very soon (I migrated and re-organized everything onto a [new account](https://github.com/VinLudens)) and since this issue is technically not related to my work here, I wanted to close it (at least in this repo).

If you want to, I'll be happy to open one [over here](https://github.com/VinLudens/ARR-004_Kyou-Yamai-Bunko) just to keep the issue around. If you're fine with closing this, I shall wish you all the best and farewell buddy!
